version: '3'
services:
  querycenter-back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: "querycenter-backend:0.0.1"
    container_name: querycenter-back-end
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    networks:
      - querycenter-network

  querycenter-front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "querycenter-frontend:0.0.1"
    container_name: querycenter-front-end
    ports:
      - "3000:3000"
    networks:
      - querycenter-network
    links:
      - querycenter-back-end

networks:
  querycenter-network:
    driver: bridge
